
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# Activar el modo de desarrollo únicamente cuando se indique en el entorno.
DEBUG = os.getenv("DJANGO_DEBUG", "false").strip().lower() in {
    "1", "true", "yes", "on",
}


def _enabled(name):
    return os.getenv(name, "false").strip().lower() in {
        "1", "true", "yes", "on",
    }

def _comma_separated_env(name, default=""):
    return [
        value.strip()
        for value in os.getenv(name, default).split(",")
        if value.strip()
    ]


ALLOWED_HOSTS = _comma_separated_env("DJANGO_ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "corsheaders",
    "accounts",
    "customers",
    "devices",
    "orders",
    "inventory",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

_db_options = {}
if os.getenv("DB_SSLMODE"):
    _db_options["sslmode"] = os.environ["DB_SSLMODE"]
if os.getenv("DB_SSLROOTCERT"):
    _db_options["sslrootcert"] = os.environ["DB_SSLROOTCERT"]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "OPTIONS": _db_options,
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.1/topics/auth/password_validation/

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/

if DEBUG:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.console.EmailBackend",
        },
    }
else:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "OPTIONS": {
                "host": os.getenv("DJANGO_SMTP_HOST", "localhost"),
                "port": int(os.getenv("DJANGO_SMTP_PORT", "25")),
                "username": os.getenv("DJANGO_SMTP_USERNAME", ""),
                "password": os.getenv("DJANGO_SMTP_PASSWORD", ""),
                "use_tls": _enabled("DJANGO_SMTP_USE_TLS"),
                "timeout": 10,
            },
        },
    }

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

CORS_ALLOWED_ORIGINS = _comma_separated_env(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173" if DEBUG else "",
)
CSRF_TRUSTED_ORIGINS = _comma_separated_env("DJANGO_CSRF_TRUSTED_ORIGINS")

# Las cookies de Django admin y CSRF solo circulan sobre HTTPS en producción.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Activar el redireccionamiento al confirmar el proxy HTTPS del host. El proxy
# debe sobrescribir X-Forwarded-Proto y Gunicorn debe aceptar solo tráfico suyo.
SECURE_SSL_REDIRECT = _enabled("DJANGO_SECURE_SSL_REDIRECT")
if _enabled("DJANGO_TRUST_X_FORWARDED_PROTO"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Empezar con una duración corta solo después de probar HTTPS extremo a extremo.
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "0"))


# Evidencias fotográficas privadas
MEDIA_ROOT = Path(
    os.getenv("DJANGO_PRIVATE_MEDIA_ROOT", str(BASE_DIR / "private_media"))
)

# Tamaño objetivo de cada fotografía: 10 MB
EVIDENCE_MAX_FILE_SIZE = 10 * 1024 * 1024

# Máximo absoluto permitido antes de procesarla: 20 MB
EVIDENCE_MAX_UPLOAD_SIZE = 20 * 1024 * 1024
