# Generated by Django 6.1.1 on 2026-09-23 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderevidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTechnicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('repair_actions', models.TextField()),
                ('repair_observations', models.TextField(blank=True)),
                ('parts_description', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('REPARADO', 'Reparado'), ('PARCIAL', 'Reparado parcialmente'), ('NO_REPARABLE', 'No reparable'), ('SIN_FALLA', 'Sin falla detectada')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_reports_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_report', to='orders.serviceorder')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_reports_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTechnicalReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('diagnosis', models.TextField()),
                ('repair_actions', models.TextField()),
                ('repair_observations', models.TextField(blank=True)),
                ('parts_description', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('REPARADO', 'Reparado'), ('PARCIAL', 'Reparado parcialmente'), ('NO_REPARABLE', 'No reparable'), ('SIN_FALLA', 'Sin falla detectada')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_report_changes', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.ordertechnicalreport')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_report_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['revision'],
                'constraints': [models.UniqueConstraint(fields=('report', 'revision'), name='unique_technical_report_revision')],
            },
        ),
    ]
