# Generated by Django 6.1.1 on 2026-09-24 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordertechnicalreport_ordertechnicalreporthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Ingresado'), ('DIAGNOSIS', 'Diagnóstico'), ('AUTHORIZATION', 'Autorización'), ('PART', 'Espera de repuesto'), ('REPAIR', 'Reparación'), ('TESTING', 'Pruebas'), ('READY', 'Listo para retiro'), ('DELIVERED', 'Entregado'), ('CLOSED', 'Cerrado'), ('REJECTED', 'No reparado/rechazado')], default='RECEIVED', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('RECEIVED', 'Ingresado'), ('DIAGNOSIS', 'Diagnóstico'), ('AUTHORIZATION', 'Autorización'), ('PART', 'Espera de repuesto'), ('REPAIR', 'Reparación'), ('TESTING', 'Pruebas'), ('READY', 'Listo para retiro'), ('DELIVERED', 'Entregado'), ('CLOSED', 'Cerrado'), ('REJECTED', 'No reparado/rechazado')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('RECEIVED', 'Ingresado'), ('DIAGNOSIS', 'Diagnóstico'), ('AUTHORIZATION', 'Autorización'), ('PART', 'Espera de repuesto'), ('REPAIR', 'Reparación'), ('TESTING', 'Pruebas'), ('READY', 'Listo para retiro'), ('DELIVERED', 'Entregado'), ('CLOSED', 'Cerrado'), ('REJECTED', 'No reparado/rechazado')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='orders.serviceorder')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
    ]
