# Generated by Django 6.1.1 on 2026-09-25 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0006_orderfinancial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_type', models.CharField(choices=[('SERVICE', 'Garantía del servicio'), ('PART', 'Garantía de repuesto')], max_length=10)),
                ('is_applicable', models.BooleanField(default=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranties', to='orders.serviceorder')),
                ('order_part', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranty', to='inventory.orderpart')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderWarrantyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATED', 'Creación'), ('UPDATED', 'Actualización')], max_length=10)),
                ('warranty_type', models.CharField(choices=[('SERVICE', 'Garantía del servicio'), ('PART', 'Garantía de repuesto')], max_length=10)),
                ('is_applicable', models.BooleanField()),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True)),
                ('change_note', models.TextField(blank=True)),
                ('changed_by_username', models.CharField(blank=True, max_length=150)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_history', to='orders.serviceorder')),
                ('order_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranty_history', to='inventory.orderpart')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='orders.orderwarranty')),
            ],
            options={
                'ordering': ['revision'],
            },
        ),
        migrations.AddConstraint(
            model_name='orderwarranty',
            constraint=models.UniqueConstraint(condition=models.Q(('warranty_type', 'SERVICE')), fields=('order',), name='unique_service_warranty_per_order'),
        ),
        migrations.AddConstraint(
            model_name='orderwarranty',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order_part__isnull', True), ('warranty_type', 'SERVICE')), models.Q(('order_part__isnull', False), ('warranty_type', 'PART')), _connector='OR'), name='warranty_type_matches_part'),
        ),
        migrations.AddConstraint(
            model_name='orderwarranty',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ends_on__isnull', True), ('is_applicable', False), ('starts_on__isnull', True)), models.Q(('ends_on__gte', models.F('starts_on')), ('ends_on__isnull', False), ('is_applicable', True), ('starts_on__isnull', False)), _connector='OR'), name='warranty_valid_date_range'),
        ),
        migrations.AddConstraint(
            model_name='orderwarrantyhistory',
            constraint=models.UniqueConstraint(fields=('warranty', 'revision'), name='unique_warranty_revision'),
        ),
    ]
