# Generated by Django 6.1.1 on 2026-09-28 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderviabilityassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderwarrantyhistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Creación'), ('UPDATED', 'Actualización'), ('DELETED', 'Eliminación')], max_length=10),
        ),
        migrations.AlterField(
            model_name='orderwarrantyhistory',
            name='warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='orders.orderwarranty'),
        ),
    ]
