# Generated by Django 6.1.1 on 2026-09-30 04:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import orders.warranty_request_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderwarrantyhistory_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateField(default=django.utils.timezone.localdate)),
                ('problem_description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente')], default='PENDING', max_length=20)),
                ('concurrent_open_reason', models.TextField(blank=True)),
                ('client_name_snapshot', models.CharField(editable=False, max_length=150)),
                ('client_rut_snapshot', models.CharField(editable=False, max_length=20)),
                ('evidence', models.ImageField(blank=True, null=True, upload_to=orders.warranty_request_models.warranty_request_evidence_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('created_by_username', models.CharField(blank=True, editable=False, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_requests_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_requests', to='orders.serviceorder')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='orders.orderwarranty')),
            ],
            options={
                'ordering': ['-requested_on', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATED', 'Creación'), ('UPDATED', 'Actualización'), ('STATUS_CHANGED', 'Cambio de estado')], max_length=20)),
                ('from_status', models.CharField(blank=True, choices=[('PENDING', 'Pendiente')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('PENDING', 'Pendiente')], max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('changed_by_username', models.CharField(blank=True, max_length=150)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_request_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='orders.warrantyrequest')),
            ],
            options={
                'ordering': ['revision', 'id'],
                'constraints': [models.UniqueConstraint(fields=('request', 'revision'), name='unique_warranty_request_revision')],
            },
        ),
    ]
