# Generated by Django 6.1.1 on 2026-09-30 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_warrantyrequest_warrantyrequesthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyrequesthistory',
            name='changed_by_role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='warrantyrequesthistory',
            name='decision',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('AWAITING_APPROVAL', 'Pendiente de aprobación'), ('CHANGES_REQUESTED', 'Correcciones solicitadas'), ('RESOLVED', 'Resuelta')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='warrantyrequesthistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Creación'), ('UPDATED', 'Actualización'), ('STATUS_CHANGED', 'Cambio de estado'), ('TECH_PROPOSAL', 'Propuesta técnica enviada'), ('CHANGES_REQUESTED', 'Correcciones solicitadas'), ('RESOLVED', 'Resolución administrativa'), ('ADMIN_NOTE', 'Observación administrativa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='warrantyrequesthistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('AWAITING_APPROVAL', 'Pendiente de aprobación'), ('CHANGES_REQUESTED', 'Correcciones solicitadas'), ('RESOLVED', 'Resuelta')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyrequesthistory',
            name='to_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('AWAITING_APPROVAL', 'Pendiente de aprobación'), ('CHANGES_REQUESTED', 'Correcciones solicitadas'), ('RESOLVED', 'Resuelta')], max_length=20),
        ),
        migrations.CreateModel(
            name='WarrantyRequestResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada')], max_length=10)),
                ('rationale', models.TextField()),
                ('action_type', models.CharField(blank=True, choices=[('REPAIR', 'Reparación'), ('PART_REPLACEMENT', 'Cambio de repuesto'), ('OTHER', 'Otra')], max_length=30, null=True)),
                ('action_description', models.TextField(blank=True)),
                ('resolved_by_username', models.CharField(blank=True, editable=False, max_length=150)),
                ('resolved_by_role', models.CharField(blank=True, editable=False, max_length=20)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resolution', to='orders.warrantyrequest')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_request_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyRequestProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('technical_rationale', models.TextField()),
                ('action_type', models.CharField(choices=[('REPAIR', 'Reparación'), ('PART_REPLACEMENT', 'Cambio de repuesto'), ('OTHER', 'Otra')], max_length=30)),
                ('action_description', models.TextField()),
                ('proposed_by_username', models.CharField(blank=True, editable=False, max_length=150)),
                ('proposed_by_role', models.CharField(blank=True, editable=False, max_length=20)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_request_proposals', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='orders.warrantyrequest')),
            ],
            options={
                'ordering': ['revision', 'id'],
                'constraints': [models.UniqueConstraint(fields=('request', 'revision'), name='unique_warranty_request_proposal_revision')],
            },
        ),
    ]
