# Generated by Django 6.1.1 on 2026-10-01 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderwarrantyhistory_warranty_id_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSensitiveChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('CLIENT', 'Cliente asociado'), ('EQUIPMENT', 'Equipo asociado'), ('REPORTED_ISSUE', 'Problema reportado'), ('INITIAL_OBSERVATIONS', 'Observaciones iniciales')], max_length=30)),
                ('old_value', models.JSONField()),
                ('new_value', models.JSONField()),
                ('reason', models.TextField(blank=True)),
                ('changed_by_username', models.CharField(blank=True, max_length=150)),
                ('changed_by_role', models.CharField(blank=True, max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_sensitive_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensitive_change_history', to='orders.serviceorder')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
    ]
