<script setup>
import {computed,ref} from 'vue'; import AdminLayout from '../layouts/AdminLayout.vue'; import PageHeader from '../components/PageHeader.vue'; import {store,statusLabels} from '../mockStore'
const start=ref('2026-09-01'),end=ref('2026-09-30')
const rows=computed(()=>store.orders)
const counts=computed(()=>Object.fromEntries(Object.keys(statusLabels).map(k=>[k,rows.value.filter(o=>o.status===k).length])))
const maxCount=computed(()=>Math.max(1,...Object.values(counts.value)))
const avgTech=computed(()=>Math.round(rows.value.reduce((s,o)=>s+(o.times?.technical||0),0)/Math.max(1,rows.value.length)))
const avgTotal=computed(()=>Math.round(rows.value.reduce((s,o)=>s+(o.times?.total||0),0)/Math.max(1,rows.value.length)))
function fmt(sec){const d=Math.floor(sec/86400),h=Math.floor((sec%86400)/3600),m=Math.floor((sec%3600)/60);return [d?`${d} d`:'',h?`${h} h`:'',`${m} min`].filter(Boolean).join(' ')}
</script>
<template><AdminLayout><PageHeader>Indicadores operacionales<template #subtitle>Métricas simuladas desde los datos ficticios del prototipo.</template><template #actions><div class="d-flex gap-2"><input v-model="start" type="date" class="form-control form-control-sm"><input v-model="end" type="date" class="form-control form-control-sm"></div></template></PageHeader><div class="mock-note mb-4">Los indicadores de esta versión son demostrativos. La lógica real de cálculo quedará para el backend.</div><div class="row g-3 mb-4"><div class="col-6 col-xl-3"><div class="mc-card metric"><div class="value">{{rows.length}}</div><div class="mc-muted">Órdenes recibidas</div></div></div><div class="col-6 col-xl-3"><div class="mc-card metric"><div class="value">{{counts.CLOSED+counts.DELIVERED}}</div><div class="mc-muted">Órdenes cerradas</div></div></div><div class="col-6 col-xl-3"><div class="mc-card metric"><div class="value">{{fmt(avgTech)}}</div><div class="mc-muted">Tiempo técnico promedio</div></div></div><div class="col-6 col-xl-3"><div class="mc-card metric"><div class="value">{{fmt(avgTotal)}}</div><div class="mc-muted">Tiempo total promedio</div></div></div></div><div class="row g-3"><div class="col-lg-7"><div class="mc-card p-4"><h5>Órdenes por estado</h5><div v-for="(n,k) in counts" class="mt-3"><div class="d-flex justify-content-between small"><span>{{statusLabels[k]}}</span><strong>{{n}}</strong></div><div class="bar-track mt-1"><div class="bar-fill" :style="{width:(n/maxCount*100)+'%'}"></div></div></div></div></div><div class="col-lg-5"><div class="mc-card p-4"><h5>Fuente de cálculo</h5><p class="text-muted">Para esta entrega, las cifras provienen del conjunto de datos ficticios cargado en el navegador.</p><div class="alert alert-light border small mb-0"><i class="bi bi-info-circle me-1"></i>En el MVP integrado, estos valores deberán obtenerse desde órdenes persistidas y filtros reales por período.</div></div></div></div></AdminLayout></template>
