<script setup>
import {ref,computed} from 'vue'; import {useRoute} from 'vue-router'; import AdminLayout from '../layouts/AdminLayout.vue'; import PageHeader from '../components/PageHeader.vue'; import StatusBadge from '../components/StatusBadge.vue'; import {getOrder,statusLabels,statusOrder,updateOrderStatus,persist} from '../mockStore'
const route=useRoute(),order=getOrder(route.params.id),tab=ref('resumen'),message=ref(''),newStatus=ref(order?.status||'RECEIVED'),note=ref(''),authResult=ref('Autorizado'),authChannel=ref('Mensajería'),authNotes=ref(''),fileName=ref('')
const user=JSON.parse(localStorage.getItem('martini_demo_user')||'{}'); const canTechnical=['ADMIN','TECH'].includes(user.role)
function fmt(sec){sec=Number(sec||0);const d=Math.floor(sec/86400),h=Math.floor((sec%86400)/3600),m=Math.floor((sec%3600)/60);return [d?`${d} d`:'',h?`${h} h`:'',`${m} min`].filter(Boolean).join(' ')}
function save(){order.margin=Math.max(0,Number(order.price||0)-Number(order.costs||0));persist();message.value='Cambios guardados en el prototipo local.'}
function changeStatus(){updateOrderStatus(order,newStatus.value,note.value);note.value='';message.value='Estado actualizado en la demostración.'}
function registerAuth(){order.history.push(['AUTHORIZATION','Autorización',new Date().toISOString(),`${authResult.value} vía ${authChannel.value}. ${authNotes.value}`]);persist();message.value='Autorización registrada de forma ficticia.'}
function evidence(e){fileName.value=e.target.files?.[0]?.name||'';if(fileName.value)message.value='Fotografía seleccionada solo para demostración. No se sube a ningún servidor.'}
const marginPct=computed(()=>Number(order?.price)>0?Math.round(Number(order.margin)/Number(order.price)*100):0)
</script>
<template><AdminLayout>
<div v-if="!order" class="alert alert-warning">Orden no encontrada.</div>
<template v-else>
<PageHeader>{{order.code}} <StatusBadge :status="order.status" :label="statusLabels[order.status]"/><template #subtitle>{{order.device_name}} · Cliente: {{order.client_name}} · Responsable: {{order.assigned_name}}</template><template #actions><button v-if="canTechnical" class="btn btn-primary" @click="tab='linea'">Actualizar estado</button></template></PageHeader>
<div v-if="message" class="alert alert-success py-2">{{message}}</div>
<div class="section-tabs mb-4"><button v-for="t in [['resumen','Resumen'],['diagnostico','Diagnóstico'],['linea','Línea de tiempo'],['evidencias','Evidencias'],['repuestos','Repuestos y costos'],['garantia','Garantía'],['viabilidad','Índice de viabilidad']]" :class="{active:tab===t[0]}" @click="tab=t[0]">{{t[1]}}</button></div>
<section v-if="tab==='resumen'" class="row g-3"><div class="col-lg-8"><div class="mc-card p-4 h-100"><h5>Información general</h5><div class="row g-3 mt-1"><div class="col-md-6"><div class="mc-muted small">Equipo</div><strong>{{order.device_name}}</strong></div><div class="col-md-6"><div class="mc-muted small">Estado actual</div><StatusBadge :status="order.status" :label="statusLabels[order.status]"/></div><div class="col-md-6"><div class="mc-muted small">Falla reportada</div>{{order.reported_issue}}</div><div class="col-md-6"><div class="mc-muted small">Ingreso</div>{{new Date(order.created_at).toLocaleString('es-CL')}}</div><div class="col-md-6"><div class="mc-muted small">Diagnóstico actual</div>{{order.diagnosis||'Pendiente'}}</div><div class="col-md-6"><div class="mc-muted small">Trabajo realizado</div>{{order.repair_work||'Pendiente'}}</div></div></div></div><div class="col-lg-4"><div class="mc-card p-4"><h5>Tiempos del servicio</h5><table class="table small mb-0"><tbody><tr><td>Tiempo técnico</td><td class="text-end fw-semibold">{{fmt(order.times.technical)}}</td></tr><tr><td>Espera autorización</td><td class="text-end">{{fmt(order.times.authorization)}}</td></tr><tr><td>Espera repuesto</td><td class="text-end">{{fmt(order.times.part)}}</td></tr><tr><td>Espera cliente</td><td class="text-end">{{fmt(order.times.client)}}</td></tr><tr class="fw-bold"><td>Total</td><td class="text-end">{{fmt(order.times.total)}}</td></tr></tbody></table></div></div></section>
<section v-if="tab==='diagnostico'" class="mc-card p-4"><h5>Diagnóstico y reparación</h5><p class="screen-note">Campos interactivos solo para validar la experiencia de usuario.</p><label class="form-label mt-3">Diagnóstico definitivo</label><textarea v-model="order.diagnosis" class="form-control mb-3" rows="4"></textarea><label class="form-label">Reparación realizada</label><textarea v-model="order.repair_work" class="form-control mb-3" rows="4"></textarea><label class="form-label">Observaciones internas</label><textarea v-model="order.observations" class="form-control mb-3" rows="3"></textarea><button class="btn btn-primary" @click="save">Guardar cambios demo</button></section>
<section v-if="tab==='linea'" class="row g-4"><div class="col-lg-7"><div class="mc-card p-4"><h5>Línea de tiempo</h5><div class="timeline mt-4"><div class="timeline-item" v-for="ev in [...order.history].reverse()"><div class="fw-semibold">{{ev[1]}}</div><div class="small text-muted">{{new Date(ev[2]).toLocaleString('es-CL')}}</div><div class="mt-1">{{ev[3]}}</div></div></div></div></div><div class="col-lg-5"><div class="mc-card p-4"><h5>Actualizar estado</h5><label class="form-label mt-3">Nuevo estado</label><select v-model="newStatus" class="form-select mb-3"><option v-for="s in statusOrder" :value="s">{{statusLabels[s]}}</option><option value="REJECTED">No reparado/rechazado</option></select><label class="form-label">Observación</label><textarea v-model="note" class="form-control mb-3" rows="3"></textarea><button class="btn btn-primary" @click="changeStatus">Guardar actualización</button></div><div class="mc-card p-4 mt-3"><h5>Registro interno de autorización</h5><p class="small text-muted">La autorización se obtiene fuera de la plataforma; aquí solo se deja constancia.</p><select v-model="authResult" class="form-select mb-2"><option>Autorizado</option><option>Pendiente</option><option>Rechazado</option></select><select v-model="authChannel" class="form-select mb-2"><option>Mensajería</option><option>Teléfono</option><option>Presencial</option><option>Otro</option></select><textarea v-model="authNotes" class="form-control mb-2" placeholder="Observaciones"></textarea><button class="btn btn-outline-primary" @click="registerAuth">Registrar autorización demo</button></div></div></section>
<section v-if="tab==='evidencias'" class="mc-card p-4"><h5>Evidencias</h5><p class="text-muted small">Las fotografías deben ser ficticias o anonimizadas. En este prototipo no se envían archivos.</p><div class="row g-3"><div class="col-md-6"><input type="file" accept="image/*" class="form-control" @change="evidence"></div><div class="col-md-6"><div class="fake-photo"><span v-if="fileName"><i class="bi bi-image me-2"></i>{{fileName}}</span><span v-else>Vista previa simulada</span></div></div></div></section>
<section v-if="tab==='repuestos'" class="row g-3"><div class="col-lg-7"><div class="mc-card p-4"><h5>Repuestos asociados</h5><table class="table"><thead><tr><th>Repuesto</th><th>Proveedor</th><th>Costo</th></tr></thead><tbody><tr><td>Pantalla compatible</td><td>Proveedor A</td><td>${{Number(order.costs||0).toLocaleString('es-CL')}}</td></tr></tbody></table></div></div><div class="col-lg-5"><div class="mc-card p-4"><h5>Precio, costos y margen</h5><label class="form-label">Precio cobrado</label><input v-model.number="order.price" type="number" class="form-control mb-2"><label class="form-label">Costos directos</label><input v-model.number="order.costs" type="number" class="form-control mb-2"><button class="btn btn-primary mb-3" @click="save">Recalcular</button><div class="border-top pt-3"><div class="d-flex justify-content-between"><span>Margen estimado</span><strong>${{Number(order.margin||0).toLocaleString('es-CL')}}</strong></div><div class="small text-muted">{{marginPct}}% del precio</div></div></div></div></section>
<section v-if="tab==='garantia'" class="mc-card p-4"><h5>Garantía</h5><div class="row g-3"><div class="col-md-4"><label class="form-label">Estado</label><select class="form-select"><option>Vigente</option><option>Vencida</option><option>Utilizada</option></select></div><div class="col-md-4"><label class="form-label">Inicio</label><input type="date" class="form-control" value="2026-09-12"></div><div class="col-md-4"><label class="form-label">Término</label><input type="date" class="form-control" value="2026-12-12"></div><div class="col-12"><label class="form-label">Condiciones</label><textarea class="form-control" rows="3">Garantía por funcionamiento del repuesto instalado.</textarea></div></div></section>
<section v-if="tab==='viabilidad'" class="row g-3"><div class="col-lg-4"><div class="mc-card p-4 text-center"><div class="score-circle mx-auto"><div class="fs-3 fw-bold">{{order.viability.score}}</div><div class="small">/100</div></div><h5 class="mt-3">{{order.viability.label}}</h5><p class="small text-muted mb-0">Resultado orientativo. La decisión final corresponde al técnico.</p></div></div><div class="col-lg-8"><div class="mc-card p-4"><h5>Factores considerados</h5><table class="table mb-3"><tbody><tr><td>Dificultad técnica</td><td class="text-end fw-semibold">{{order.viability.difficulty}}</td></tr><tr><td>Disponibilidad/costo del repuesto</td><td class="text-end fw-semibold">{{order.viability.part}} / {{order.viability.cost}}</td></tr><tr><td>Margen estimado</td><td class="text-end fw-semibold">{{order.viability.margin}}</td></tr><tr><td>Tiempo requerido</td><td class="text-end fw-semibold">{{order.viability.time}}</td></tr><tr><td>Riesgo de garantía</td><td class="text-end fw-semibold">{{order.viability.warranty}}</td></tr></tbody></table><div class="alert alert-light border mb-0"><strong>Explicación:</strong> la disponibilidad del repuesto y el margen favorecen el resultado; la dificultad y el tiempo pueden reducirlo. Esta versión no ejecuta una regla real de negocio.</div></div></div></section>
</template>
</AdminLayout></template>
