# Generated by Django 6.1.1 on 2026-09-30 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPartCorrectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('QUANTITY', 'Cantidad'), ('NOTE', 'Nota')], max_length=20)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_part_corrections', to=settings.AUTH_USER_MODEL)),
                ('order_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_history', to='inventory.orderpart')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
    ]
