# Generated by Django 6.1.1 on 2026-09-30 09:34

from django.db import migrations, models


def backfill_actor_snapshot(apps, schema_editor):
    history_model = apps.get_model('inventory', 'OrderPartCorrectionHistory')
    for entry in history_model.objects.using(schema_editor.connection.alias).filter(
        changed_by__isnull=False,
    ).select_related('changed_by').iterator():
        history_model.objects.using(schema_editor.connection.alias).filter(
            pk=entry.pk,
        ).update(
            changed_by_username=entry.changed_by.username,
            changed_by_role=entry.changed_by.role or '',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_orderpartcorrectionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpartcorrectionhistory',
            name='changed_by_role',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='orderpartcorrectionhistory',
            name='changed_by_username',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.RunPython(backfill_actor_snapshot, migrations.RunPython.noop),
    ]
