<script setup>
import { ref, computed } from 'vue'; import { useRouter } from 'vue-router'; import AdminLayout from '../layouts/AdminLayout.vue'; import PageHeader from '../components/PageHeader.vue'; import {store,createOrder,persist} from '../mockStore'
const router=useRouter(),step=ref(1),error=ref(''),mode=ref('existing'),clientId=ref(''),newClient=ref({name:'',phone:'',email:''}),device=ref({type:'Celular',brand:'',model:'',identifier:''}),order=ref({reported_issue:'',observations:'',assigned_name:'Técnico 1'})
const selected=computed(()=>store.clients.find(c=>String(c.id)===String(clientId.value)))
function next(){error.value='';if(step.value===1){if(mode.value==='existing'&&!clientId.value){error.value='Selecciona un cliente.';return}if(mode.value==='new'&&!newClient.value.name){error.value='Ingresa el nombre del cliente.';return}if(!device.value.brand||!device.value.model){error.value='Marca y modelo son obligatorios.';return}}if(step.value===2&&!order.value.reported_issue){error.value='Describe la falla reportada.';return}step.value++}
function save(){
  let client=selected.value
  if(mode.value==='new'){
    const id=Math.max(0,...store.clients.map(c=>c.id))+1
    client={id,...newClient.value,devices:[]};store.clients.push(client)
  }
  const did=Math.max(0,...store.clients.flatMap(c=>c.devices||[]).map(d=>d.id))+1
  client.devices.push({id:did,type:device.value.type,brand:device.value.brand,model:device.value.model,identifier:device.value.identifier||'Sin identificador'})
  persist()
  const created=createOrder({clientId:client.id,client_name:client.name,device_name:`${device.value.brand} ${device.value.model}`,reported_issue:order.value.reported_issue,observations:order.value.observations,assigned_name:order.value.assigned_name})
  router.push(`/ordenes/${created.id}`)
}
</script>
<template><AdminLayout>
<PageHeader>Nueva orden de servicio<template #subtitle>Registro simplificado en tres pasos.</template><template #actions><router-link to="/ordenes" class="btn btn-outline-secondary">Cancelar</router-link></template></PageHeader>
<div class="mc-card p-4"><div class="d-flex flex-wrap gap-3 mb-4"><div v-for="n in 3" class="d-flex align-items-center gap-2"><span class="badge rounded-pill" :class="step>=n?'text-bg-primary':'text-bg-light'">{{n}}</span><span class="small fw-semibold">{{n===1?'Cliente y equipo':n===2?'Recepción':'Revisión'}}</span></div></div><div v-if="error" class="alert alert-danger">{{error}}</div>
<section v-if="step===1"><h5>Cliente y equipo</h5><div class="row g-4 mt-1"><div class="col-lg-5"><div class="btn-group mb-3"><button class="btn btn-sm" :class="mode==='existing'?'btn-primary':'btn-outline-primary'" @click="mode='existing'">Existente</button><button class="btn btn-sm" :class="mode==='new'?'btn-primary':'btn-outline-primary'" @click="mode='new'">Nuevo cliente</button></div><div v-if="mode==='existing'"><label class="form-label">Cliente</label><select v-model="clientId" class="form-select"><option value="">Seleccionar...</option><option v-for="c in store.clients" :value="c.id">{{c.name}} · {{c.phone}}</option></select></div><div v-else><label class="form-label">Nombre</label><input v-model="newClient.name" class="form-control mb-2"><label class="form-label">Teléfono</label><input v-model="newClient.phone" class="form-control mb-2"><label class="form-label">Correo</label><input v-model="newClient.email" class="form-control"></div></div><div class="col-lg-7"><div class="row g-3"><div class="col-md-4"><label class="form-label">Tipo</label><select v-model="device.type" class="form-select"><option>Celular</option><option>Computador</option><option>Tablet</option><option>Otro</option></select></div><div class="col-md-4"><label class="form-label">Marca</label><input v-model="device.brand" class="form-control"></div><div class="col-md-4"><label class="form-label">Modelo</label><input v-model="device.model" class="form-control"></div><div class="col-12"><label class="form-label">IMEI / Serie</label><input v-model="device.identifier" class="form-control" placeholder="Opcional"></div></div></div></div></section>
<section v-if="step===2"><h5>Recepción</h5><label class="form-label mt-3">Falla o síntoma reportado</label><textarea v-model="order.reported_issue" class="form-control mb-3" rows="4"></textarea><label class="form-label">Observaciones de ingreso</label><textarea v-model="order.observations" class="form-control mb-3" rows="3"></textarea><label class="form-label">Responsable</label><select v-model="order.assigned_name" class="form-select"><option>Técnico 1</option><option>Técnico 2</option><option>Sin asignar</option></select></section>
<section v-if="step===3"><h5>Revisión</h5><div class="row g-3 mt-2"><div class="col-md-6"><div class="mc-card p-3"><div class="small text-muted">Cliente</div><strong>{{mode==='existing'?selected?.name:newClient.name}}</strong><hr><div class="small text-muted">Equipo</div><strong>{{device.brand}} {{device.model}}</strong><div class="small text-muted">{{device.identifier||'Sin identificador'}}</div></div></div><div class="col-md-6"><div class="mc-card p-3"><div class="small text-muted">Falla reportada</div><strong>{{order.reported_issue}}</strong><hr><div class="small text-muted">Responsable</div><strong>{{order.assigned_name}}</strong></div></div></div></section>
<div class="d-flex justify-content-between mt-4"><button class="btn btn-outline-secondary" @click="step--" :disabled="step===1">Anterior</button><button v-if="step<3" class="btn btn-primary" @click="next">Siguiente <i class="bi bi-arrow-right ms-1"></i></button><button v-else class="btn btn-primary" @click="save">Crear orden demo</button></div></div>
</AdminLayout></template>
